version: '{build}'
image: Visual Studio 2017
configuration: Release
before_build:
  - nuget restore src\compute.sln
build:
  project: src\compute.sln
  verbosity: minimal
after_build:
  - 7z a -tzip -r compute-%APPVEYOR_BUILD_VERSION%.zip src\bin\Release\*
artifacts:
  - path: compute-$(APPVEYOR_BUILD_VERSION).zip
